name: Xcode - Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          xcodebuild clean -workspace Deez_Metaverse.xcworkspace -scheme Deez_Metaverse
          xcodebuild clean -project Deez_Metaverse.xcodeproj -scheme Deez_Metaverse
          xcodebuild build -workspace Deez_Metaverse.xcworkspace -scheme Deez_Metaverse
          xcodebuild archive -workspace Deez_Metaverse.xcworkspace -scheme Deez_Metaverse -archivePath /Users/abdeljaliljabiri/Downloads/Deez_Meta/Deez_Metaverse.xcarchive
          xcodebuild -exportArchive -archivePath ~/Downloads/Deez_Meta/Deez_Metaverse.xcarchive -exportPath ~/Downloads/Deez_Meta -exportOptionsPlist /Users/abdeljaliljabiri/Downloads/Deez_Meta/Deez_Metaverseu/ExportOptions.plist 

